# Generated by Django 6.0.7 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_subtask_owner_task_owner_alter_subtask_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_notified_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
